version: '3.6'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "7000:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=pass
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    restart: always

  app:
    build:
      dockerfile: app.Dockerfile
    ports:
      - "8088:8088"
    command: /app/api
    depends_on:
        rabbitmq:
            condition: service_healthy